version: '3'

tasks:
  run-event-reading:
    desc: "Sends the event reading request using httpyac"
    cmds:
      - httpyac event-reading.http
    silent: false

  retry-nats:
    desc: "Run application startup script in retry-nats mode"
    cmds:
      - chmod +x ./start.sh
      - ./start.sh retry-nats
    silent: false
