spring:
  application:
    name: b3proj
  nats:
    port: ${NATS_PORT:4222}
    topic-name: desktop-sysinfo
    host: ${NATS_HOST:localhost}

logging:
  level:
    root: ${COLLECTOR_LOG_LEVEL:INFO}
server:
  port: ${COLLECTOR_LISTEN_PORT:8080}
collector:
  id: ${COLLECTOR_ID:dev}
